<?php

namespace app\modules\admin\controllers;

use Codeception\Module\DumbHelper;
use yii\helpers\VarDumper;

class VkController extends \yii\web\Controller
{

    const VIKTOR_ID = "907609";

    const GET_CHAT = 'messages.getChat';
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionSet() {
        return "7993a609";
    }


    public function actionApi()
    {

       $response = vkApi_messagesSend(self::VIKTOR_ID, ' i am vk-bot!');
       my_var_dump($response);
        return $this->render('index');
    }





}
