<?php

namespace app\modules\programmer\controllers;

use app\components\Mdb;
use app\models\Sale;
use app\models\SaleFilters;
use app\models\SaleFiltersSearch;
use app\models\Renders;

class ViewsController extends \yii\web\Controller
{

    public function init()
    {
        $this->layout = "@app/views/layouts/debug.php";
        parent::init(); // TODO: Change the autogenerated stub
    }


    public function actionIndex()
    {
        return $this->render('index');
    }
    public function beforeAction($action)
    {
      //  Renders::StaticView('layouts/_screensize');
        return parent::beforeAction($action);
    }

    public function actionGetScreenSize()
    {

        return $this->render('index');
    }

    public function actionMenu()
    {
        return $this->render('menu');
    }

    public function actionAlert()
    {
        Mdb::Alert(" HELLO I AM ALET MESSAGE ", SUCCESS);
        return $this->render('index');
    }


    public function actionCheckBox()
    {
        return $this->render('checkbox');
    }


    public function actionSaleSearchForm()
    {
        $salefilter = SaleFilters::findOne(229);
        return $this->render('_sale_search_grid.php', ['salefilter' => $salefilter]);
    }

    public function actionOneSale()
    {

        $model = Sale::find()->where(['s.id' => 1456])
            ->from(['s' => Sale::tableName()])
            ->joinWith(['agent AS agent'])
            ->joinWith(['addresses AS address'])
            ->joinWith(['similar AS sim'])
            ->joinWith(['similarSales1 AS sims'])
            ->one();


      //  $sale = Sale::findOne(1456);
        $controls = true;

        $salefilter = new SaleFilters();
        $salefilter->id = 898;
        return $this->render('_sale-table.php', compact(['model', 'controls', 'salefilter']));
    }

    public function actionPreloader() {
        $this->enableCsrfValidation = false;
        return $this->render('tools/_preloader');
    }
public function actionOneSaleModerate()
    {

        $model = Sale::find()->where(['s.id' => 1456])
            ->from(['s' => Sale::tableName()])
            ->joinWith(['agent AS agent'])
            ->joinWith(['addresses AS address'])
            ->joinWith(['similar AS sim'])
            ->joinWith(['similarSales1 AS sims'])
            ->one();


      //  $sale = Sale::findOne(1456);
        $controls = true;

        $salefilter = new SaleFilters();
        $salefilter->id = 898;
        return $this->render('_moderate_view.php', compact(['model', 'controls', 'salefilter']));
    }

    public function actionOneSaleInform()
    {

        $sale = Sale::findOne(1456);
        echo strip_tags($sale->renderLong_title() . " " . $sale->description);
        return $this->render('index');
    }

    public function actionMiniOneSale()
    {

        $sale = Sale::findOne(1456);
        $controls = true;
        $contacts = true;

        $salefilter = new SaleFilters();
        $salefilter->id = 898;
        return $this->render('_mini-sale.php', compact(['sale', 'controls', 'salefilter', 'contacts']));
    }

    public function actionMiniOneSales()
    {

        $sales = Sale::find()->where(['between', 'id', 150, 450])->limit(10)->all();
        $controls = true;
        $contacts = true;

        $salefilter = new SaleFilters();
        $salefilter->id = 898;
        return $this->render('_mini-sales.php', compact(['sales', 'controls', 'salefilter', 'contacts']));

    }

    public function actionSaleFilterSearchForm()
    {
        $model = new SaleFiltersSearch();

        return $this->render('salefilters/_search.php', compact(['model']));
    }

    public function actionOneSaleFilter()
    {
        $model = SaleFilters::findOne(207);

        return $this->render('salefilters/_view.php', compact(['model']));
    }

    public function actionSearchByFilter()
    {
        $model = SaleFilters::findOne(207);


        return $this->render('_search_by_filter.php', compact(['model']));
    }


}
