<?php

namespace app\modules\programmer\controllers;

use Codeception\Module\DumbHelper;
use yii\helpers\VarDumper;
use app\models\Notifications;

class VkController extends \yii\web\Controller
{

    const VIKTOR_ID = "907609";

    const GET_CHAT = 'messages.getChat';
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionSet() {
        return "7993a609";
    }


    public function actionApi()
    {

       $response = vkApi_messagesSend(self::VIKTOR_ID, ' i am vk-bot!');
       my_var_dump($response);
        return $this->render('index');
    }

    public function actionButtons()
    {
        $kbd = [
            'one_time' => false,
            'buttons' => [
                [Notifications::getBtn("Покажи мой ID", Notifications::COLOR_DEFAULT, Notifications::CMD_ID)],
                [Notifications::getBtn("Далее", Notifications::COLOR_PRIMARY, Notifications::CMD_NEXT)],
            ]
        ];



       $response = Notifications::vkApi_messagesSend(self::VIKTOR_ID, ' i am vk-bot!', $kbd
           );
       my_var_dump($response);
        return $this->render('index');
    }









}
