<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "app_errors".
 *
 * @property integer $id
 * @property integer $fatality
 * @property string $name
 */
class Errors extends \yii\db\ActiveRecord
{

    const FATAL_ERROR = 1;
    const FATAL_ERROR_COURSE = 2;
    const FATAL_ERROR_COURSE_COUNTED = 3;
    const NOTICE_ERROR = 4;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'app_errors';
    }

    public static function Fatalities()
    {
        return [
            self::FATAL_ERROR => 'FATAL_ERROR',
            self::FATAL_ERROR_COURSE => "FATAL_ERROR_COURSE",
            self::FATAL_ERROR_COURSE_COUNTED => "FATAL_ERROR_COURSE_COUNTED ОШИБКА",
            self::NOTICE_ERROR => 'NOTICE_ERROR'

        ];
    }

    public function renderFatality($type_error = 0)
    {
        if ($type_error) return self::Fatalities()[$type_error];
    }

    public static function getMap()
    {
        return ArrayHelper::map(self::find()->all(), 'id', 'name');
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['fatality', 'name', 'id'], 'required'],
            [['fatality', 'id'], 'integer'],
            [['name'], 'string', 'max' => 256],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'fatality' => 'Fatality',
            'name' => 'Name',
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        $body = "<?php \r\n";
        $errors = Errors::find()->all();
        if ($errors) {
            foreach ($errors as $error) {
                $body .= "DEFINE('".$error->name."',".$error->id.");\r\n";
            }
            file_put_contents('error_const.php',$body);
        }

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
